screwdriver-cd/sd-cmd

README.md, config/config.go, executor/executor.go, screwdriver/api/api.go, screwdriver/api/api_test.go, screwdriver/store/store.go, screwdriver/store/store_test.go, sd-cmd.go, util/util.go, util/util_test.go
Can get response from Screwdriver API and Store.
To execute binary, we need to make it possible to get command information and the binary from Screwdriver API and Store, thus I implement this features.
Execute binary command procedure is as follows
1. Get command information from Screwdriver API
2. Get the binary from Store
3. Exec the binary
In this PR is about 1 and 2 features.
There is no /v4/commands/ now, thus I created this by using mock which referenced from [command design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md).
[command design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md)
=> feat: Get sd-cmd from Screwdriver API and Store

executor/binary.go, executor/binary_test.go, sd-cmd.go
Follow the change of [command design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md#formats),  fix sd-cmd to install binary command to `/opt/sd/commands/<namespace>/<name>/<version>/Binary.File`.
Also I fixed the panic log which output string not bytes.
I ran this command at local.
Fixed the path to install binary command. Also I added the test to check the binary command path.
[command design formats](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md#formats)
=> fix: save binary command as Binary.File

screwdriver/api/api.go
In https://github.com/screwdriver-cd/data-schema/pull/199/files , `pipelineId` was added to `command`. 
To respond that, I add `pipelineId` to Command struct.
Add `pipelineId` to Command struct.
=> fix: add pipelineId to command struct

screwdriver/api/api.go
PipelineId is not string but int.
Change pipelineId type from string to int.
=> fix: fix pipelineId type

executor/binary.go, screwdriver/api/api.go, screwdriver/store/store.go, screwdriver/store/store_test.go
We added `auth` to `GET` commands in screwdriver-store(https://github.com/screwdriver-cd/store/pull/30). Therefore, we have to add authorization header to `GET` request to screwdriver-store.
Pass SDToken when create new store client, and use it to get commands from screwdriver-store.
https://github.com/screwdriver-cd/store/pull/30
=> fix: Use token to get command from store

executor/binary.go, executor/binary_test.go, executor/executor_test.go
Now if binary.file contains directory, it will fail to install binary file because sd-cmd tries to install binary to non-existent directory. 
So I fixed to install binary to exist directory.
When install binary, just get binary file name from binary.file.
=> fix: install path of binary file

config/config.go, config/config_test.go
- Put binaries downloaded under `/sd/commands` we are guaranteed that `/sd` will exist when the build starts since that's where the source code locates. 
- `/opt/sd` is a share mount between the base host and the vm for k8s-vm, ideally, we want the mount to be read-only and no remount to r/w should be allowed. Will take care of that later when we have a good solution.
=> fix: make base path for cmds configurable

executor/executor.go
Currently, we have to click 6 times to display command log in the build page. It is too troublesome.
Therefore, we changed the log path and log file name, and shortened the number of clicks to display the command log.
Create the command log under `SDArtifactsDir/.sd/commands`, and name `{timestamp}-{namespace}-{name}.log`.
By changing this way, we can display command log by clicking 3 times.
And it is still distinguishable each log of commands when some commands are executed in the build.
=> fix: Change command log path and file name.

executor/binary_test.go, executor/executor.go, executor/executor_test.go, executor/habitat.go, executor/habitat_test.go, sd-cmd.go
habitat format and docker format of `sd-cmd` are not yet implemented.
This PR provides `remote` mode of habitat format function.
I'll implement `local` mode after merging this PR.
It works in local SD like this:
- sd-command.yaml
```
(...snip)
format: habitat
habitat:
mode: remote
package: core/node8
command: node
```
- screen shot
Related: https://github.com/screwdriver-cd/screwdriver/issues/677
Design Doc: https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md
=> feat(677): habitat format

executor/executor.go, sd-cmd.go
`sd-cmd` doesn't return actual exit code. It returns only `1` with failure.
This PR fixes to return actual exit code.
- A command doesn't exist (This is the same behavior with current `sd-cmd`)
- An error happens in `sd-cmd`
- https://stackoverflow.com/questions/10385551/get-exit-code-go
- Related: https://github.com/screwdriver-cd/screwdriver/issues/677
=> fix(677): return actual exit code

executor/binary.go, executor/binary_test.go
Currently, `sd-cmd binary` downloads a binary file via the Store API each time it executes its file.
This behavior misspends network traffic and time, if you will execute `sd-cmd binary` repeatedly.
This PR makes it possible to download and install a binary file only once.
=> fix: improve binary command installation.

executor/executor_test.go, promoter/promoter.go, promoter/promoter_test.go, publisher/publisher_test.go, screwdriver/api/api.go, screwdriver/api/api_test.go, sd-cmd.go, util/util.go, validator/validator_test.go
This PR adds `sd-cmd promote namespace/name version tag` command.
It works locally like below:
- when we tag first time
- when we use already used tag
- (added) when we tag with same version
Related:
- design: https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md 
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/677
=> feat(677): implement promote command

README.md, publisher/publisher.go, publisher/publisher_test.go
This PR provides a feature of publish with tag specified by `-t` option. It works locally like below:
- default is `latest` (`$ sd-cmd publish -f sd-command.yaml` )
- specify tag (`$ sd-cmd publish -f sd-command.yaml -t supertag`)
This PR also add badges to README.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/677
- design: https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md
=> feat(677): implement publish with tag feature

screwdriver/api/api.go
Screwdriver API should get binary part of multipart payload with only "binary" key. Using "habitat" or "docker" key is not reasonable.
Screwdriver API can get binary part just like `data.binary`. There is no need to add `if` block for getting data.
https://github.com/screwdriver-cd/screwdriver/pull/1135
https://github.com/screwdriver-cd/screwdriver/issues/677
=> feat(677): [1] Key of binary part of multipart payload should be "binary"

executor/habitat.go, executor/habitat_test.go
we should refer downloaded pkg path when use habitat local command.
=> fix: fix habitat local pkg install path

testdata/yaml/sd-command.yaml, util/util.go
Would be nice if users could customize the usage field in the UI.
This PR adds `usage` to command spec.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1095
=> feat(1095): Add optional usage field to command

executor/habitat.go, executor/habitat_test.go
`/hab` directory has been changed to `/opt/hab` and `/hab/bin/hab` should be `/opt/hab/bin/hab`
https://github.com/screwdriver-cd/executor-k8s/commit/a2ea4d9d46e8ae135f8fdd7cbb3dfe5efa53832d#diff-052e9d6ff615a6db485c488784e1f398R43
=> fix: Fix hab path

executor/habitat.go, executor/habitat_test.go
`/opt/hab/bin/hab` doesn't exist
Should be [`/opt/sd/bin/hab`](https://github.com/screwdriver-cd/launcher/blob/df18ce624edea9328fe9ef9ba950fc628d7190b9/Dockerfile#L76)
=> fix: hab path

.gitignore, executor/executor.go
Currently when writing data exceeding pipe capacity to the piped stdin its writing is blocked until reading it.
This PR makes its writing asynchronous by the goroutine.
I will add a functional test instead of an unit test later.
- https://golang.org/pkg/os/exec/#Cmd.StdinPipe
=> fix: write date to stdin pipe asynchronously.

executor/executor_test.go, publisher/publisher_test.go, removeTag/removeTag.go, removeTag/removeTag_test.go, screwdriver/api/api.go, screwdriver/api/api_test.go, sd-cmd.go, validator/validator_test.go
We want a tag remove command on sd-cmd cli.
We implement a tag remove command. We add `removeTag/` and add `RemoveTagCommand` to `screwdriver/api/api.go` for that.
https://github.com/screwdriver-cd/screwdriver/issues/2399
=> feat(2399): Add removeTag command

README.md, config/config.go, config/config_test.go, executor/executor.go, executor/executor_test.go, go.mod, go.sum, logger/logger.go, logger/logger_test.go, removeTag/removeTag.go, removeTag/removeTag_test.go, screwdriver.yaml, sd-cmd.go, util/util.go
I checked how much of the sd-cmd log file is seen, and found that almost all people don't look at the log file.
Users spend time with artifact bookend teardown even if the user does not put files to artifacts because of sd-cmd.
It is better not to create log files to speed up build time.
- Not to create log file as default.
- Able to output log files with `--debug` or `-debug` flag.
- If the debug flag is true, all logs will be written to a file, but error logs will also be output to stderr.
- refactoring surrounded code that  I wrote.
https://github.com/screwdriver-cd/screwdriver/issues/2467
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution …
=> feat(2467): [Breaking Change] Change log behave not to output log to file by default

README.md, executor/executor.go, executor/executor_test.go, promoter/promoter_test.go, publisher/publisher_test.go, removeTag/removeTag_test.go, screwdriver/api/api.go, screwdriver/api/api_test.go, validator/validator_test.go
When getting a command with sd-cmd, a lot of unnecessary logs for the user can be output.
This is noise for users checking the logs.
Add a new Verbose flag. Console output is suppressed unless this flag is turned ON. The target of suppression is the GET log when the command is acquired.
No flags:
```
$ ./sd-cmd exec screwdriver-cd-samples/sum@stable 1 2
3
```
Flag ON:
```
./sd-cmd exec -v screwdriver-cd-samples/sum@stable 1 2
2022/02/03 06:56:50 [DEBUG] GET https://***.co.jp/v4/commands/screwdriver-cd-samples/sum/stable
3
```
=> feat: Verbose mode

executor/binary.go, executor/binary_test.go, executor/executor.go, executor/executor_test.go, executor/habitat.go, executor/habitat_test.go, screwdriver/store/store.go, screwdriver/store/store_test.go
In #49 , we added the verbose option to restrict debug log.
However, the store access logs still output regardless of the verbose option.
We should also restrict the store access logs.
The store access logs also suppressed unless this flag is turned ON.
#49 
=> fix: Restrict debug store access log by verbose option

executor/binary.go, executor/habitat.go
Currently, debug logs only include when cmd is installed, when cmd is executed and how long did it take to execute cmd.
It is useful add info about cmd executed to debug logs.
Output cmd info(namespace, name and version) to debug logs.
=> fix: Add cmd info to debug logs
